### ISSUE TITLE
Meta issue for project

### ISSUE THREAD

**Issue by kgostic** [CDCgov/cfa-rt-postprocessing#3]
- [ ] Setup the repo
- [ ] Ensure repo has all needed settings for PR management, CI, etc
- [ ] Build a Docker container
- [ ] Set up the python infrastructure
- [ ] Finalize the readme, combining Zack's open issue #1 and Katie's open PR 
- [ ] Build merged_draws.parquet and merged_summaries.parquet
- [ ] Build merged_release.csv, be consistent with the format in 1CDP
- [ ] Build production database in blob storage
- [ ] Work with Nimesh, Rachel, Andrea, Hannah Cohen to release from production database to website, 1cdp, and data.cdc.gov
- [ ] Build map_data.csv files, following current schema exactly
- [ ] Build timeseries_data.csv files, following current schema exactly
- [ ] Figure out the plots
- [ ] Figure out the dashboard

**Comment by kgostic** [comment]
@natemcintosh are you using this or should we close it?

**Comment by natemcintosh** [comment]
I'm still sort of using. It's a good list of things we still need to do.
